### PR TITLE
Add default wallpaper set for GNOME

### PR DESCRIPTION
**Pull request by wroyca**
As per title, this fetch and set the default wallpaper set from GNOME. :)

https://gitlab.gnome.org/GNOME/gnome-backgrounds

### CODE REVIEW

**Comment by aguslr** [comment]
Doesn't this achieve the same thing as [using dconf](https://github.com/aguslr/bluevanilla/blob/85b55e/rootfs/etc/dconf/db/local.d/01-background) since the default background files are already stored locally?

**Comment by wroyca** [comment]
> Doesn't this achieve the same thing as [using dconf](https://github.com/aguslr/bluevanilla/blob/85b55e/rootfs/etc/dconf/db/local.d/01-background) since the default background files are already stored locally?

Hello, 

> since the default background files are already stored locally?

Are they? Last I check Fedora doesn't ship with GNOME backgrounds by default - instead, they ship their own branding ones. This little script pull GNOME backgrounds from the official repository and install them system-wide, the dconf only choose a wallpaper, that is, it doesn't pull them \:)

In this screenshot are GNOME Wallpapers (JXL only, excluding svg) and Fedora ones:

Screenshot from 2024-05-28 07-31-28

**Comment by aguslr** [comment]
> Are they? Last I check Fedora doesn't ship with GNOME backgrounds by default - instead, they ship their own branding ones.

Yes, you can find them in `/usr/share/backgrounds` along with Fedora ones. They do ship only the ones from the current GNOME release, but you can get the old ones with [Nostalgia from Flathub](https://flathub.org/apps/im.bernard.Nostalgia).

**Comment by wroyca** [comment]
> > Are they? Last I check Fedora doesn't ship with GNOME backgrounds by default - instead, they ship their own branding ones.
> 
> Yes, you can find them in `/usr/share/backgrounds` along with Fedora ones. They do ship only the ones from the current GNOME release, but you can get the old ones with [Nostalgia from Flathub](https://flathub.org/apps/im.bernard.Nostalgia).

Interesting, I recall seeing them excluded from packaging, perhaps did I confuse with ublue, thank for letting me know!

**Comment by aguslr** [comment]
> Interesting, I recall seeing them excluded from packaging, perhaps did I confuse with ublue, thank for letting me know!

No problem! BTW, [here is the code used to reset to the default GNOME wallpapers](https://github.com/aguslr/bluevanilla/blob/85b55e1d/Containerfile#L17).

**Comment by wroyca** [comment]
"Hey @aguslr, I've taken a look back again on a fresh image. I'm not sure what the rationale is behind the Fedora upstream package for gnome-backgrounds, but we are indeed missing a few from GNOME 46 release, namely (not exclusive):

 * Amber
 * Fold
 * Geometrics
 * Glass-chip 
 * Neogeo 
 * Ring 
 * Swoosh
 * Tarka
 * ...

Screenshot from 2024-05-29 11-00-30
Screenshot from 2024-05-29 11-02-34

I now remember that my PR was to pull those missing ones - I will add the rationale as a comment to the Dockerfile on my repo; let me know if you want them here as well after all, in which case I'll open another PR :)

**Comment by aguslr** [comment]
> "Hey @aguslr, I've taken a look back again on a fresh image. I'm not sure what the rationale is behind the Fedora upstream package for gnome-backgrounds, but we are indeed missing a few from GNOME 46 release, namely (not exclusive):

Yep, those are missing. I see now that they are provided by the package [`gnome-backgrounds-extras`](https://rpmfind.net/linux/RPM/fedora/40/x86_64/g/gnome-backgrounds-extras-46.0-1.fc40.noarch.html) in addition to those in [`gnome-backgrounds`](https://rpmfind.net/linux/RPM/fedora/40/x86_64/g/gnome-backgrounds-46.0-1.fc40.noarch.html).

Commit 8a1ffff should do it.

**Comment by wroyca** [comment]
> > "Hey @aguslr, I've taken a look back again on a fresh image. I'm not sure what the rationale is behind the Fedora upstream package for gnome-backgrounds, but we are indeed missing a few from GNOME 46 release, namely (not exclusive):
> 
> Yep, those are missing. I see now that they are provided by the package [`gnome-backgrounds-extras`](https://rpmfind.net/linux/RPM/fedora/40/x86_64/g/gnome-backgrounds-extras-46.0-1.fc40.noarch.html) in addition to those in [`gnome-backgrounds`](https://rpmfind.net/linux/RPM/fedora/40/x86_64/g/gnome-backgrounds-46.0-1.fc40.noarch.html).
> 
> Commit [8a1ffff](https://github.com/aguslr/bluevanilla/commit/8a1ffffc53321eaa1e352a0a61483c95645ca544) should do it.

TIL [gnome-backgrounds-extras](https://rpmfind.net/linux/RPM/fedora/40/x86_64/g/gnome-backgrounds-extras-46.0-1.fc40.noarch.html)

**Pull request closed without merging**
